-- DropForeignKey
ALTER TABLE `Posts` DROP FOREIGN KEY `Posts_GID_fkey`;

-- AddForeignKey
ALTER TABLE `Posts` ADD CONSTRAINT `Posts_GID_fkey` FOREIGN KEY (`GID`) REFERENCES `Group`(`GID`) ON DELETE CASCADE ON UPDATE CASCADE;
