-- CreateTable
CREATE TABLE `Badges` (
    `BadgeID` INTEGER NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(100) NOT NULL,
    `Description` TEXT NOT NULL,
    `Condition` TEXT NOT NULL,

    PRIMARY KEY (`BadgeID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Comments` (
    `CommentID` INTEGER NOT NULL AUTO_INCREMENT,
    `PostID` INTEGER NOT NULL,
    `Nickname` VARCHAR(50) NOT NULL,
    `Content` TEXT NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    `CreatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`CommentID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Group` (
    `GID` INTEGER NOT NULL AUTO_INCREMENT,
    `GName` VARCHAR(100) NOT NULL,
    `GImage` VARCHAR(255) NULL,
    `GIntro` TEXT NULL,
    `IsPublic` BOOLEAN NOT NULL,
    `GPassword` VARCHAR(255) NOT NULL,
    `CreatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `GLikes` INTEGER NOT NULL DEFAULT 0,
    `GBadgeCount` INTEGER NOT NULL DEFAULT 0,
    `PostCount` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`GID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Group_Badge` (
    `GID` INTEGER NOT NULL,
    `BadgeID` INTEGER NOT NULL,
    `ObtainedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`GID`, `BadgeID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Posts` (
    `PostID` INTEGER NOT NULL AUTO_INCREMENT,
    `GID` INTEGER NOT NULL,
    `Nickname` VARCHAR(51) NOT NULL,
    `Title` VARCHAR(100) NOT NULL,
    `Image` VARCHAR(255) NULL,
    `Content` TEXT NOT NULL,
    `Location` VARCHAR(100) NULL,
    `MemoryMoment` DATETIME(3) NOT NULL,
    `IsPublic` BOOLEAN NOT NULL,
    `PPassword` VARCHAR(255) NOT NULL,
    `CreatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LikeCount` INTEGER NOT NULL DEFAULT 0,
    `CommentCount` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`PostID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Post_Tag` (
    `PostID` INTEGER NOT NULL,
    `TagID` INTEGER NOT NULL,

    PRIMARY KEY (`PostID`, `TagID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Tags` (
    `TagID` INTEGER NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`TagID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Comments` ADD CONSTRAINT `Comments_PostID_fkey` FOREIGN KEY (`PostID`) REFERENCES `Posts`(`PostID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Group_Badge` ADD CONSTRAINT `Group_Badge_GID_fkey` FOREIGN KEY (`GID`) REFERENCES `Group`(`GID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Group_Badge` ADD CONSTRAINT `Group_Badge_BadgeID_fkey` FOREIGN KEY (`BadgeID`) REFERENCES `Badges`(`BadgeID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Posts` ADD CONSTRAINT `Posts_GID_fkey` FOREIGN KEY (`GID`) REFERENCES `Group`(`GID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Post_Tag` ADD CONSTRAINT `Post_Tag_PostID_fkey` FOREIGN KEY (`PostID`) REFERENCES `Posts`(`PostID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Post_Tag` ADD CONSTRAINT `Post_Tag_TagID_fkey` FOREIGN KEY (`TagID`) REFERENCES `Tags`(`TagID`) ON DELETE RESTRICT ON UPDATE CASCADE;
